### PR TITLE
Add iOS Swift 3 Demo

### PR DESCRIPTION
**Pull request by hansemannn**
So this PR moves the existing Objective-C demo to `objc/keyframes-sample-ios` and introduces the Swift demo in `swift/keyframes-sample-ios`.

### CODE REVIEW

**Comment by hansemannn** [comment]
CLA signed

**Comment by lozzle** [comment]
Sorry for the delayed response!  I think the .swift files need to have headers which reference the LICENSE/PATENTS files in the root like the other files in the repo

**Comment by hansemannn** [comment]
@lozzle Sure thing, updated the headers!

**Comment by LazyChild** [comment]
Thank you for adding swift demo!

Could you move files under `swift/keyframes-sample-ios` to `swift/`,
so that it shares a similar folder structure as `objc`.

If there's no test provided could we simply remove the Tests folder

**Comment by hansemannn** [comment]
@LazyChild Makes sense, updated the PR 🚀.

**Comment by LazyChild** [comment]
@hansemannn Thank you! Looks good to me. Lets squash the commits and I will merge it

**Comment by hansemannn** [comment]
@LazyChild You can select squash-merge on Github and it will do it automatically :-)

**Comment by LazyChild** [comment]
@hansemannn thank you :) good to know

**Comment by caroait** [comment]
@hansemannn Thanks for the demo! Do you know if It's possible to create animations and add them into diferente images? To make it more dynamic

**Pull request merged**
