### PR TITLE
Update and rename README.html to README.md

### PR DESCRIPTION
**Pull request by OUeasley**
README was html and was not being rendered correctly on GitHub.

### CODE REVIEW

**Comment by subtleGradient** [comment]
This README.html was meant to be viewed on the desktop by animators using Adobe After Effects. They are much less likely to be using GitHub or have an app that is capable of properly rendering MarkDown format.

That being said, I greatly appreciate that you took the time to convert this file over to MarkDown!

**Comment by OUeasley** [comment]
Ah alright well I shall close the PR then! Good day.

**Comment by subtleGradient** [comment]
Actually, let's just have both files!
Can you change your commit to add the md file instead of replacing the html file?

**Comment by subtleGradient** [comment]
Oh dang. I edited the HTML after you made this PR. Can you rebase do it'll merge cleanly? Thanks. Sorry

**Comment by OUeasley** [comment]
@subtleGradient No problem!

**Pull request merged**
